spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

turbine:
  clusterNameExpression: new String("default")
  appConfig: MICRO-SERVICE-USER
  combineHostPort: true
